boot: Fix ASN.1 for mbedtls >= 3.1
zephyrproject-rtos/mcuboot pull request #118
Opened 2024-07-01 20:00 UTC by d3zd3z

In Mbed TLS 3.1, the private fields in the ASN.1 structure were made private. This breaks code that accesses these private macros.

Fix this by changing the ASN.1 specific code to use a new field accessor `ASN1_CONTEXT_MEMBER` that will be conditionally defined based on the version of Mbed TLS that is present.

[david.brown: Cherry-picked from upsteam]
Signed-off-by: David Brown <david.brown@linaro.org>

2024-07-03 18:59 UTC, dleach02 commented
lgtm. I would reference the sha this was cherry-picked from in the upstream in your commit message.

2024-07-03 19:00 UTC, dleach02 approved these changes

2024-07-08 06:30 UTC, nordicjm requested changes
We do not accept patches here, this follows `main` only

2024-07-08 19:26 UTC, d3zd3z commented
> We do not accept patches here, this follows `main` only

This is literally a change cherry-picked from upstream. Without it, rsa doesn't build. I will update the commit to include the commit that was cherry-picked.

2024-07-09 06:39 UTC, nordicjm commented
Have opened a sync PR here: https://github.com/zephyrproject-rtos/zephyr/pull/75634

2024-07-09 06:39 UTC, nordicjm commented
> > We do not accept patches here, this follows `main` only
> 
> This is literally a change cherry-picked from upstream. Without it, rsa doesn't build. I will update the commit to include the commit that was cherry-picked.

**We do not accept patches here, period**. This branch follows upstream `main`, no exceptions.

2024-07-09 14:50 UTC, de-nordic commented
> @nordicjm This is now just migrated to upstream. Debatable whether we should be pulling in additional changes that aren't needed to fix the bug.

We synchronize the MCUboot to this fork as often as we can. This actually works better then having separate features being brought here via PRs; this also gives us linear history with the same sha as in upstream, which means that anyone is free to substitute Zephyr fork with mcu-tools/mcuboot main and does not need to deal with conflicts.
Previously we had to deal with conflicts, evil merges, reverts, conflicts over reverts, and all of that has been even more annoying in user forks that have their own modifications over the MCUboot.

2024-07-10 06:04 UTC, merged