Synch 29 07 2021
zephyrproject-rtos/mcuboot pull request #56
Opened 2021-07-29 13:50 UTC by nvlsianpu

Synchronize up to https://github.com/mcu-tools/mcuboot/commit/994816d04a055b39de2d174930271023965e8138

Merge using **Merge by Create a Merge commit!**

2021-07-29 21:14 UTC, mbolivar-nordic approved these changes

2021-08-06 14:18 UTC, de-nordic commented
I have tested the sync on nrf52840dk_nrf52840. The serial recovery seems to work correctly. I have found two issues, that seem to be present on current main also:
 - https://github.com/mcu-tools/mcuboot/issues/1092
 - https://github.com/mcu-tools/mcuboot/issues/1091

As above issues already exist on main, they should not affect the sync.

2021-08-06 14:35 UTC, de-nordic commented
It is worth to also take bd69c3dd4b4b7cd0c8063c2d3a885c0664962bc7 with the sync, this is commit directly above sync ending commit but it enables non-peruser mcumgr commands to be handled by platform specific handler.

2021-08-06 14:40 UTC, de-nordic commented on boot/boot_serial/src/boot_serial.c
> +               hdr->nh_group >= MGMT_GROUP_ID_PERUSER) {
Worth taking https://github.com/zephyrproject-rtos/mcuboot/commit/bd69c3dd4b4b7cd0c8063c2d3a885c0664962bc7 in, that removes this line.

2021-08-10 07:00 UTC, de-nordic approved these changes
Looks OK.

I have tested most common functionalities on nrf52840dk, and everything seems to work OK.
Allowed myself to pull in one more commit: bd69c3dd4b4b7cd0c8063c2d3a885c0664962bc7, moving the Sync head up by one notch.

2021-08-14 00:07 UTC, mnkp requested changes
#mcu-tools/mcuboot/pull/1040 introduced a regression, as a result MCUboot does not build on the following boards: 96b_carbon, hexiwear_k64, nucleo_f401re, stm32f0_disco.

2021-08-17 07:40 UTC, nvlsianpu commented
^^ pending fix https://github.com/mcu-tools/mcuboot/issues/1101

2021-08-17 15:04 UTC, nvlsianpu commented
Awaiting for https://github.com/mcu-tools/mcuboot/pull/1101
Synchronization will be reapplied again to the upstream SHA with that patch.

2021-08-19 14:01 UTC, nvlsianpu commented
@mnkp I moved synchronization point ahead so this contains fix for the issue you had mentioned now.

2021-08-19 17:59 UTC, mnkp approved these changes

2021-08-19 18:01 UTC, utzig commented
@nvlsianpu You should just disable the CI for this repo, there's no point in running the same upstream tests again...

2021-08-19 18:01 UTC, utzig approved these changes

2021-08-31 10:03 UTC, carlescufi commented
@d3zd3z there was this upmerge before you posted yours, so we probably need to close this one now.

2021-08-31 23:57 UTC, d3zd3z commented
I'm fine with closing this one. Mine is one commit behind, which includes the release notes for 1.8.0-rc1, which we can include if we want.

2021-11-02 10:13 UTC, closed without merging