boot/espressif: Support passing custom mbedtls path
zephyrproject-rtos/mcuboot pull request #65
Opened 2021-10-28 17:19 UTC by shubhamkulkarni97

Currently mbedtls path is hardcoded in the CMakeLists.txt

This PR adds an ability to pass custom mbedtls path and removes dependency on manual submodule update command

2021-11-01 13:28 UTC, tejlmand commented
> In case of option 2, can we perform this sync?

@nvlsianpu and @d3zd3z I'll leave that decision to you two.

2021-11-01 13:43 UTC, utzig commented
> > In case of option 2, can we perform this sync?
> 
> @nvlsianpu and @d3zd3z I'll leave that decision to you two.

@sylvioalves Yes, you can send upstream PR and after the merge build a sync yourself, like it's usually done.

2021-11-01 19:14 UTC, sylvioalves commented
> @sylvioalves Yes, you can send upstream PR and after the merge build a sync yourself, like it's usually done.

@utzig Upstream porting is completed as is. No PR needed. So I can submit a PR in this very same repo with necessary sync from upstream, right?

2021-11-02 08:33 UTC, nvlsianpu requested changes
Synchronization with the upstream is preferred instead.

2021-11-02 10:04 UTC, nvlsianpu commented
I opened synchronization PR: https://github.com/zephyrproject-rtos/mcuboot/pull/66

2021-11-02 10:25 UTC, closed without merging